# Generated by Django 4.0.4 on 2022-05-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Title',
            new_name='title',
        ),
    ]
